from __future__ import annotations

from pathlib import Path
from typing import Protocol


class ObjectStorageClient(Protocol):
    def put_object(self, key: str, data: bytes, content_type: str = "application/octet-stream") -> str: ...
    def get_presigned_url(self, key: str, expires_in: int = 3600) -> str: ...
    def delete_object(self, key: str) -> None: ...
    def public_url(self, key: str) -> str: ...
    def list_objects(self, prefix: str) -> list[str]: ...
    def download_to_file(self, key: str, local_path: Path | str) -> None: ...
