from __future__ import annotations

from typing import Protocol


class ObjectStorageClient(Protocol):
    def put_object(self, key: str, data: bytes, content_type: str = "application/octet-stream") -> str: ...
    def get_presigned_url(self, key: str, expires_in: int = 3600) -> str: ...
    def delete_object(self, key: str) -> None: ...
    def public_url(self, key: str) -> str: ...
